version: '3'

services:

  server:
<<<<<<< HEAD
    image: omegalab/test-ci-server:latest
=======

    image: 951264400542.dkr.ecr.us-east-2.amazonaws.com/app2:latest
>>>>>>> 8da6d586183284f50c4cb94a36e5c6d26fb3b999
    container_name: test-ci-server
    restart: always
    networks:
      dis_net:
        ipv4_address: 172.16.201.20
    expose:
      - 2501
    ports:
      - 2501:2501

  client:
<<<<<<< HEAD
    image: omegalab/test-ci-client:latest
=======

    image: 951264400542.dkr.ecr.us-east-2.amazonaws.com/app2
>>>>>>> 8da6d586183284f50c4cb94a36e5c6d26fb3b999
    container_name: test-ci-client
    restart: always
    networks:
      dis_net:
        ipv4_address: 172.16.201.100
    expose:
      - 82
    ports:
      - 82:82
    links:
      - server

##

##
##
networks:
  dis_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.201.0/24
##
##
