version: '3'

services:

  server:

    image: 951264400542.dkr.ecr.us-east-2.amazonaws.com/app2:latest
    container_name: test-ci-server
    restart: always
    networks:
      dis_net:
        ipv4_address: 172.16.201.20
    expose:
      - 2501
    ports:
      - 2501:2501

  client:

    image: 951264400542.dkr.ecr.us-east-2.amazonaws.com/app2
    container_name: test-ci-client
    restart: always
    networks:
      dis_net:
        ipv4_address: 172.16.201.100
    expose:
      - 82
    ports:
      - 82:82
    links:
      - server

##

##
##
networks:
  dis_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.201.0/24
##
##
