version: '3'

services:

  server:
    image: omegalab/test-ci-server:latest
    container_name: test-ci-server
    restart: always
    networks:
      dis_net:
        ipv4_address: 172.16.201.20
    expose:
      - 2501
    ports:
      - 2501:2501

  client:
    image: omegalab/test-ci-client:latest
    container_name: test-ci-client
    restart: always
    networks:
      dis_net:
        ipv4_address: 172.16.201.100
    expose:
      - 80
    ports:
      - 80:80
    links:
      - server

##

##
##
networks:
  dis_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.201.0/24
##
##
